stages:
  - stage
  - production

staging:
  stage: stage
  before_script:
    - export NOW=$(date +%Y%m%d%M%S)
    - 'curl -s -X POST -H ''Content-type: application/json'' --data "{''text'':''Deployment STARTED $CI_PROJECT_NAME in $CI_JOB_STAGE by $GITLAB_USER_LOGIN Details: $CI_PIPELINE_URL''}" $SLACK_WEBHOOK_NOTIFICATION_URL'
  script:
    - echo Installing software
    - export PATH=$PATH:/usr/local/go/bin
    - echo Attempting build
    - go get -v 
    - go build -ldflags="-X main.Build=${NOW}" -o api-${NOW} main.go
    - ls -oah api*
  after_script:
    - echo Deploying build to S3
    - export FILENAME=`ls -1 api*`
    - export NOW=`echo $FILENAME | cut -d"-" -f2`
    - aws s3 cp $FILENAME s3://$S3_DEPLOY_BUCKET/$S3_BUCKET_FOLDER/$NOW/api/$FILENAME
    - echo Syncing build to server and restart nginx
    - ssh root@$SERVER_STAGING 'bash -s' < scripts/push_server.sh $S3_DEPLOY_BUCKET $S3_BUCKET_FOLDER $NOW $FILENAME
    - echo New live api is $FILENAME
    - 'curl -s -X POST -H ''Content-type: application/json'' --data "{''text'':''Deployment COMPLETE $CI_PROJECT_NAME in $CI_JOB_STAGE successfully by $GITLAB_USER_LOGIN :rocket: Details: $CI_PIPELINE_URL''}" $SLACK_WEBHOOK_NOTIFICATION_URL'
  only:
    - dev
  tags:
    - learnt
  environment: staging

production:
  stage: production
  before_script:
    - export NOW=$(date +%Y%m%d%M%S)
    - 'curl -s -X POST -H ''Content-type: application/json'' --data "{''text'':''Deployment STARTED $CI_PROJECT_NAME in $CI_JOB_STAGE by $GITLAB_USER_LOGIN Details: $CI_PIPELINE_URL''}" $SLACK_WEBHOOK_NOTIFICATION_URL'
  script:
    - echo Installing software
    - export PATH=$PATH:/usr/local/go/bin
    - echo Attempting build
    - go get -v
    - go build -ldflags="-X main.Build=${NOW}" -o api-${NOW} main.go
    - ls -oah api*
  after_script:
    - echo Deploying build to S3
    - export FILENAME=`ls -1 api*`
    - export NOW=`echo $FILENAME | cut -d"-" -f2`
    - aws s3 cp $FILENAME s3://$S3_DEPLOY_BUCKET/$S3_BUCKET_FOLDER/$NOW/api/$FILENAME
    - echo Syncing build to server and restart nginx
    - ssh root@$SERVER_PRODUCTION 'bash -s' < scripts/push_server.sh $S3_DEPLOY_BUCKET $S3_BUCKET_FOLDER $NOW $FILENAME
    - echo New live api is $FILENAME
    - 'curl -s -X POST -H ''Content-type: application/json'' --data "{''text'':''Deployment COMPLETE $CI_PROJECT_NAME in $CI_JOB_STAGE successfully by $GITLAB_USER_LOGIN :rocket: Details: $CI_PIPELINE_URL''}" $SLACK_WEBHOOK_NOTIFICATION_URL'
  only:
    - master
  tags:
    - learnt
  environment: production
