app:
  listen: 0.0.0.0:5050
  data: ./uploads
  search_miles: 50
  env: dev
  debug: true
  payload: ./payload/payload.json
  temp: ./tmp
  jobs: true
  enable_sms: true

storage:
  uri: mongodb://localhost:27017/tutoring
  database: tutoring
  user:
  password:
  ssl: false
  certificate:
  timeout: 5

security:
  token: F41EF9AE1433F3A8

websocket:
  origins: 

payments:
  commission: 30
  student_referral_reward: 10
  student_signup_reward: 10
  tutor_referral_reward: 50

mail:
  smtp:
    host: smtp.google.com
    user: test@gmail.com
    pass: test
  from:
    email: hello@tutoring.io
    name: tutoring

lessons:
  advance_duration: 1m

messenger:
  require_approval: false

service:
  twitter:
    key: 
    secret: 
  linkedin:
    key: 
    secret: 
  facebook:
    key: 
    secret: 
  google:
    key: 
    secret: 
  outlook:
    key: 
    secret: 
  yahoo:
    key: 
    secret: 
  amazon:
    key: 
    secret: 
    bucket: 
  stripe:
    key: 
    secret: 
    coporate_charge_customer: 
  twilio:
    account: 
    account_token: 
    token: 
    secret: 
    phone: 
  mandrill:
    user: 
    key: 
  checkr:
    key: 
  bgcheck:
    auth:
    package: 
  intercom:
    token: =
